import React, { createContext, useContext, useState, ReactNode } from "react";

type Lang = "en" | "es";

const translations = {
  en: {
    brand: "CTRL+",
    tagline: "by TaxForYou",
    login: "Log In",
    register: "Register",
    name: "Full Name",
    email: "Email",
    phone: "Phone",
    country: "Country",
    password: "Password",
    confirmPassword: "Confirm Password",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    createAccount: "Create your account",
    welcomeBack: "Welcome back",
    checkEmail: "Check your email",
    confirmEmailSent: "We sent a confirmation link to your email. Please verify to continue.",
    dashboard: "Dashboard",
    upload: "Upload Statement",
    uploadDesc: "Drag & drop your bank statement or click to browse",
    supportedFormats: "Supported formats: PDF, CSV, XLSX",
    analyze: "Analyze Statement",
    analyzing: "Analyzing...",
    analysisError: "Could not analyze this document.",
    results: "Results",
    totalSpent: "Total Spent",
    topCategory: "Top Category",
    transactions: "Transactions",
    expenseBreakdown: "Expense Breakdown",
    logout: "Log Out",
    category: "Category",
    amount: "Amount",
    percentage: "Percentage",
    backToDashboard: "Back to Dashboard",
    welcome: "Welcome",
    uploadYourStatement: "Upload your bank statement to get detailed spending insights",
    dragDrop: "Drag & drop file here",
    orClick: "or click to browse",
    selectCountry: "Select country",
    downloadReport: "Download Report",
    adminPanel: "Admin Panel",
    allUsers: "All Users",
    noUsers: "No users found",
    userDeleted: "User deleted successfully",
    actions: "Actions",
    joined: "Joined",
    selectMultiple: "(you can select multiple)",
    loadingText: "Loading...",
    userFallback: "User",
    aiAnalysisLabel: "AI Analysis",
    formatsLabel: "Formats",
    plReportLabel: "P&L Report",
    professionalWord: "Professional",
    fileWord: "file",
    readyWord: "ready",
    clickOrDragAddMore: "+ Click or drag to add more",
    analyzingWord: "Analyzing",
    errorWord: "error(s)",
    analysesSavedWord: "analysis/analyses saved.",
    checkHistoryDuplicateWarning: "Check History — if two statements turn out to be for the same period, we'll flag it there so you can delete the one that doesn't belong.",
    couldNotReadFile: "Could not read the file.",
    analyzerCouldNotRead: "The analyzer could not read this file.",
    analyzerNoResults: "The analyzer did not return any results.",
    clientsNav: "Clients",
    clientsPageTitle: "Clients",
    clientsPageDesc: "Shared across everyone who logs in — add, rename, and remove clients here.",
    addClient: "Add client",
    clientNamePlaceholder: "Client name (e.g. TAXFOURYOU INC)",
    noClientsYet: "No clients yet. Add the first one above.",
    statementsCountLabel: "statements",
    editWord: "Edit",
    saveWord: "Save",
    cancelWord: "Cancel",
    clientCreated: "Client added.",
    clientRenamed: "Client renamed.",
    clientDeleted: "Client deleted.",
    clientDuplicateError: "A client with that name already exists.",
    clientDeleteBlockedError: "This client has statements linked to it — remove or reassign those first.",
    confirmDeleteClient: "Delete this client? This cannot be undone.",
    clientNameEmptyError: "Enter a client name.",
    searchClientsPlaceholder: "Search clients...",
    viewHistoryWord: "History",
  },
  es: {
    brand: "CTRL+",
    tagline: "por TaxForYou",
    login: "Iniciar Sesión",
    register: "Registrarse",
    name: "Nombre Completo",
    email: "Correo Electrónico",
    phone: "Teléfono",
    country: "País",
    password: "Contraseña",
    confirmPassword: "Confirmar Contraseña",
    noAccount: "¿No tienes cuenta?",
    hasAccount: "¿Ya tienes cuenta?",
    createAccount: "Crea tu cuenta",
    welcomeBack: "Bienvenido de nuevo",
    checkEmail: "Revisa tu correo",
    confirmEmailSent: "Enviamos un enlace de confirmación a tu correo. Verifica para continuar.",
    dashboard: "Panel",
    upload: "Subir Estado de Cuenta",
    uploadDesc: "Arrastra y suelta tu estado de cuenta o haz clic para buscar",
    supportedFormats: "Formatos soportados: PDF, CSV, XLSX",
    analyze: "Analizar Estado",
    analyzing: "Analizando...",
    analysisError: "No se pudo analizar este documento.",
    results: "Resultados",
    totalSpent: "Total Gastado",
    topCategory: "Categoría Principal",
    transactions: "Transacciones",
    expenseBreakdown: "Desglose de Gastos",
    logout: "Cerrar Sesión",
    category: "Categoría",
    amount: "Monto",
    percentage: "Porcentaje",
    backToDashboard: "Volver al Panel",
    welcome: "Bienvenido",
    uploadYourStatement: "Sube tu estado de cuenta para obtener información detallada de gastos",
    dragDrop: "Arrastra y suelta aquí",
    orClick: "o haz clic para buscar",
    selectCountry: "Seleccionar país",
    downloadReport: "Descargar Reporte",
    adminPanel: "Panel de Administración",
    allUsers: "Todos los Usuarios",
    noUsers: "No se encontraron usuarios",
    userDeleted: "Usuario eliminado exitosamente",
    actions: "Acciones",
    joined: "Registrado",
    selectMultiple: "(puedes seleccionar varios)",
    loadingText: "Cargando...",
    userFallback: "Usuario",
    aiAnalysisLabel: "Análisis IA",
    formatsLabel: "Formatos",
    plReportLabel: "Reporte P&L",
    professionalWord: "Profesional",
    fileWord: "archivo",
    readyWord: "listo",
    clickOrDragAddMore: "+ Haz clic o arrastra para añadir más",
    analyzingWord: "Analizando",
    errorWord: "error(es)",
    analysesSavedWord: "análisis guardado(s).",
    checkHistoryDuplicateWarning: "Revisa el Historial — si dos extractos resultan ser del mismo período, ahí te avisamos para que elimines el que no corresponda.",
    couldNotReadFile: "No se pudo leer el archivo.",
    analyzerCouldNotRead: "El analizador no pudo leer este archivo.",
    analyzerNoResults: "El analizador no devolvió resultados.",
    clientsNav: "Clientes",
    clientsPageTitle: "Clientes",
    clientsPageDesc: "Compartido entre todos los que inician sesión — agrega, renombra y elimina clientes aquí.",
    addClient: "Agregar cliente",
    clientNamePlaceholder: "Nombre del cliente (ej. TAXFOURYOU INC)",
    noClientsYet: "Aún no hay clientes. Agrega el primero arriba.",
    statementsCountLabel: "extractos",
    editWord: "Editar",
    saveWord: "Guardar",
    cancelWord: "Cancelar",
    clientCreated: "Cliente agregado.",
    clientRenamed: "Cliente renombrado.",
    clientDeleted: "Cliente eliminado.",
    clientDuplicateError: "Ya existe un cliente con ese nombre.",
    clientDeleteBlockedError: "Este cliente tiene extractos asociados — elimínalos o reasígnalos primero.",
    confirmDeleteClient: "¿Eliminar este cliente? Esto no se puede deshacer.",
    clientNameEmptyError: "Escribe un nombre de cliente.",
    searchClientsPlaceholder: "Buscar clientes...",
    viewHistoryWord: "Historial",
  },
};

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: keyof typeof translations.en) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>("en");
  const t = (key: keyof typeof translations.en) => translations[lang][key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
